# Generated by Django 3.2.13 on 2022-07-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('prediction', models.CharField(choices=[('ORIENTALISM', 'orientalism'),
                                                         ('REALISM', 'realism'),
                                                         ('ANIMATION', 'animation'),
                                                         ('PENCIL_DRAWING', 'pencil_drawing'),
                                                         ('IMPRESSIONISM', 'impressionism'),
                                                         ('ABSTRACT', 'abstract'),
                                                         ('POP_ART', 'pop_art'),
                                                         ], max_length=4)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
