# Generated by Django 3.2.14 on 2022-07-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220725_0243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core_post',
        ),
    ]
